### PR TITLE
Chocolatey package for extension

### LINKED ISSUE #20: Provide a chocolatey package for the extension
## Expected Behavior
Basically be allowed to do a `choco install chocolatey-vscode` (or something similiar), instead of downloading the vsix manually and running `code --install-extension`. As well as easier to be kept up to date with new releases.

## Current Behavior
No package is provided.

## Possible Solution
Sorry, I don't really believe it's necessary to provide a solution (as you already know how to create a package 😄)

## Context

Sorry, not sure what would be valid to add here.

## Your Environment

* Module version used: 0.4.0.
* Operating System and PowerShell version: Win 10.0.17134.228, POSH: 5.1.17134.228

## Side Note
I'm willing to open a PR to provide the package (as well as integrating it into the build system).

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description
1. Full chocolatey package implementation
2. Updated build script to generate the chocolatey package
3. Added ability to push the package to chocolatey.org

## Related Issue
fixes #20 

## Motivation and Context
Easier to use for users (myself included) to install/uninstall the extension instead of trying to find the published name on VSCode extension pages.

## How Has This Been Tested?

I basically just ran the build script and checked if the package was created successfully, was able to install (unfortunately will be automatically updated to latest version it seems), and was able to uninstall.

Temporarily had to change some versions of the used addins and cake itself to make the script run (even before adding any build code myself).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. (**I think so**)
- [x] My change requires a change to the documentation. (I would suggest so)
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document. (Unfortunately missed the section about commit messages, let me know if you want me to rebase with more verbose commit messages)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Notes
Currently a work in progress, as some code for generating release notes (at a minimum) hasn't yet been included.
Would like a review (if possible) before adding it though.

### CODE REVIEW

**Comment by gep13** [comment]
>@AdmiringWorm said...
Temporarily had to change some versions of the used addins and cake itself to make the script run (even before adding any build code myself).

What sort of issues were you running into?  I haven't seen any problems.

**Comment by gep13** [comment]
>@AdmiringWorm said...
Would like a review (if possible) before adding it though.

Sorry, just saw this part.  I have made a few additional changes, and I created a new issue for adding the release notes to the nuspec as part of the build process, and for now, I have just added a link to the GitHub releases section.

**Comment by gep13** [comment]
I have just merged this here, along with some additional commits that I made:

https://github.com/gep13/chocolatey-vscode/commit/538a58819c7856d761849465336a7a497b20d76d

Apologies again for not seeing your comment.  We can continue in another PR, if you would like to tackle the adding of the release notes.

**Comment by gep13** [comment]
@AdmiringWorm I also added an additional criteria to the task to cover the failed build here:

https://ci.appveyor.com/project/GaryEwanPark/chocolatey-vscode/builds/20624766#L400

This way, it should only attempt the push to Chocolatey.org on tagged master build.

**Comment by AdmiringWorm** [comment]
> Apologies again for not seeing your comment. We can continue in another PR, if you would like to tackle the adding of the release notes.

I'll review again which errors I got when trying to run.
I forgot to take notes 😄

**Comment by gep13** [comment]
@AdmiringWorm thank you very much for doing this work, I really appreciate it!

**Comment by AdmiringWorm** [comment]
well, the first run which downloads cake 0.30 throws out an error that `MagicChunks.Cake` doesn't support it because it references Cake.Core 0.23.0.

After changing Cake.Core to 0.23.0, it throws out an error that Cake.Vscode, Cake.Npm and Cake.AppVeyor is referencing even older versions.

After updating those addons to the latest version, everything compiled and ran successfully.

**Comment by gep13** [comment]
@AdmiringWorm ah, that...

If you pass the argument: `--settings_skipverification=true` then it should work just fine 😄

**Comment by AdmiringWorm** [comment]
I tried that too, can't remember which error I got then. But it still didn't work

**Comment by gep13** [comment]
Hmm, that is what is happening on both the AppVeyor build, and locally on my Mac, so I would be curious about some more details, so that we can get to the bottom of it.

**Comment by AdmiringWorm** [comment]
hmm, I tried it again now, and it seems it works for me as well with that argument.

Maybe I had some kind of typo the last time I tried.

**Comment by gep13** [comment]
@AdmiringWorm ok, cool, glad we got this sorted out :smile:

**Pull request closed without merging**
