### PR TITLE
(docs) Added documentation for rules

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description
This PR adds documentation for all of the currently implemented rules.

## Motivation and Context

To have self-contained documentation of rules, with optional links to the rules provided by the package validator.

## How Has This Been Tested?

locally by running `.\build -target preview` and checked in google chrome.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
I just created a small powershell script to make the initial process of importing the rule from package validator a little easier.

**Comment by gep13** [comment]
Just so I am clear...

Are we talking about moving the documentation from the current wiki, to a Wyam generated site?

**Comment by gep13** [comment]
i.e. should the URL's that we link to go to the package validator wiki page, or should they go to this Wyam site?

**Comment by AdmiringWorm** [comment]
I would say yes, linking to the wyam site would be better IMO.

**Comment by gep13** [comment]
This looks like a great start to me! 👍

**Comment by gep13** [comment]
@AdmiringWorm I have merged this here:

https://github.com/gep13/chocolatey-vscode/commit/932954ce51ba69c07641041e003909bd5899cd46

**Comment by gep13** [comment]
@AdmiringWorm your changes have been merged, thanks for your contribution 👍

**Comment by AdmiringWorm** [comment]
@gep13 was it expected that the documentation to not be published?

Seems like it was unable to because of the following message:
`Unable to publish documentation, as not all Wyam Configuration is present`

**Pull request closed without merging**
